BU/urls.py
from django.conf.urls import url
from BU import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^article_list', views.article_list, name='article_list'),
    url(r'^article', views.article, name='article'),
    url(r'^project', views.project, name='project'),
    url(r'^life', views.life, name='life'),
    url(r'^topics', views.topics, name='topics'),
    url(r'^archive', views.archive, name='archive'),
    url(r'^category', views.category, name='category'),
    url(r'^tag', views.tagPage, name='tagpage'),
    url(r'^logout$', views.do_logout, name='logout'),
    url(r'^comment$', views.comment_post, name='comment_post'),
    url(r'^ajax_login', views.ajax_login, name='ajax_login'),
    url(r'^ajax_signup', views.ajax_signup, name='ajax_signup'),
    url(r'^email', views.ajax_email, name='ajax_email'),
    url(r'^reset_password', views.reset_password, name='reset_password'),
    url(r'^like', views.likes_set, name='like'),
    url(r'^avatar', views.avatar_upload, name='avatar_upload'),
    url(r'^publicate_article', views.article_publicate, name='article_publicate'),
    url(r'^userinfo', views.userinfo, name='userinfo'),
    url(r'^deletearticle', views.articleDelete, name='article_delete'),
    url(r'^editarticle', views.articleEdit, name='article_edit'),
    url(r'^search', views.search, name='search'),
    url(r'^resultpage', views.resultpage, name='resultpage'),
]

Mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Mysite import settings
import django.views.static
from BU.upload import upload_image
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^uploads/(?P<path>.*)$', django.views.static.serve, {"document_root": settings.MEDIA_ROOT, }),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/imgs/favicon.ico')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^', include('BU.urls')),
]

BU/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
import django.utils.timezone as timezone

# Create your models here.

class MyUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/%Y/%m/', default='avatar/default.png', max_length=200, blank=True, null=True, verbose_name='用户头像')
    qq = models.CharField(max_length=20, blank=True, null=True, verbose_name='QQ号码')
    mobile = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    age = models.IntegerField(blank=True, null=True, verbose_name='年龄',)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'
        db_table = 'myuser'

    def __str__(self):
        return self.username

class MenuCategory(models.Model):
    name = models.CharField(max_length=20, verbose_name='菜单栏类别')

    class Meta:
        verbose_name = '菜单栏类别'
        verbose_name_plural = '菜单栏类别'
        db_table = 'manu_category'

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称')
    index = models.IntegerField(default=999, verbose_name='分类排序')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'
        db_table = 'category'

    def __str__(self):
        return self.name

class Tags(models.Model):
    name = models.CharField(max_length=20, verbose_name='标签名称')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'
        db_table = 'tags'

    def __str__(self):
        return self.name

#自定义一个Article Model的管理器
# 1 增加一个数据处理方法
# 2 采用get_queryset的方法
class ArticleManager(models.Manager):
    def date_distinct(self):
        distinct_date_list = []
        date_list = self.values('date_publish')
        for date in date_list:
            date = date['date_publish'].strftime('%Y年%m月文章归档')
            if date not in distinct_date_list:
                distinct_date_list.append(date)
        return distinct_date_list


class Article(models.Model):
    menu_category = models.ForeignKey(MenuCategory, on_delete=models.CASCADE, verbose_name='所属菜单栏类别')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, verbose_name='分类')
    title = models.CharField(max_length=50, verbose_name='文章标题')
    content = models.TextField(verbose_name='文章内容')
    description = models.TextField(max_length=300, verbose_name='文章描述')
    author = models.ForeignKey(MyUser, verbose_name='作者', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tags, blank=True, verbose_name='标签')
    photo = models.ImageField(upload_to='articles/%Y/%m/%d/', default='articles/default.jpeg', max_length=200, blank=True, null=True, verbose_name='文章图片')
    views = models.PositiveIntegerField(default=0, verbose_name='文章阅读量')
    date_publish = models.DateTimeField(default=timezone.now, verbose_name='发布时间') # auto_now_add=True,
    objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'
        db_table = 'article'
        ordering = ['-date_publish']

    def __str__(self):
        return self.title

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

class Likes(models.Model):
    user = models.ForeignKey(MyUser, verbose_name='点赞者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '点赞'
        verbose_name_plural = '点赞'
        db_table = 'likes'

    def __str__(self):
        return str(self.user)

class Comments(models.Model):
    content = models.TextField(verbose_name='评论内容')
    date = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, blank=True, null=True, verbose_name='用户')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, blank=True, null=True, verbose_name='文章')
    pid = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='p_comment', verbose_name='父级评论')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        db_table = 'comments'

    def __str__(self):
        return str(self.id)

templates/archive.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ year }}年{{ month }}月文章</title>
{% endblock %}


{% block content %}
    <div class="container" id="content">
		<div id="article-list-page">
				<div class="row">
					<div class="col-sm-3">
						<div class="sidebar left">
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">近期文章</div>
								<div id="item-list">
									{% for article in recent_articles %}
									<a class="list-group-item" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
                                    {% endfor %}
								</div>
							</div>
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">文章归档</div>
								<div id="item-list">
									<a class="list-group-item" href="#">{{ request.GET.year }}年{{ request.GET.month }}月文章归档</a>
								</div>
							</div>

							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">分类目录</div>
								<div id="item-list">
									{% for category in category_list %}
									<a class="list-group-item" href="#">{{ category }}</a>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="article-list">
                            {% for article in pages %}
							<div class="item">
								<div class="row">
									<div class="col-sm-2">
										<div class="date">
											<span class="day">{{ article.date_publish | date:'d' }}</span>
											<span class="month">{{ article.date_publish | date:'Y-m' }}</span>
										</div>
									</div>
									<div class="col-sm-10">
										<div class="panel panel-default">
											<div class="panel-heading">
												<div class="panel-title">
													<div class="row">
														<div class="col-sm-1">
															<span class="glyphicon glyphicon-book"></span>
														</div>
														<div class="col-sm-11">
															<a class="title" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
														</div>
													</div>
												</div>
												<div class="small text-muted">
													<!-- <span class="blank"></span> -->
													<a href="#"><span class="glyphicon glyphicon-pushpin"></span>{{ article.category }}</a>-
													<a href="#"><span class="glyphicon glyphicon-user"></span>{{ article.author.username }}</a>-
													<span class="glyphicon glyphicon-tags"></span>
                                                    {% for tag in article.tags.all %}
													    <a class="tags" href="#">{{ tag.name }}</a>
                                                    {% endfor %}
												</div>
											</div>
											<div class="panel-body">
												{{ article.description}}
											</div>
											<div class="panel-footer">
												<div class="small text-muted">
													<a href="#"><span class="glyphicon glyphicon-heart"></span>{{ article.likes }}</a>
													<a href="#"><span class="glyphicon glyphicon-comment"></span>{{ article.comments_set.all.count }}</a>
													<a href="#"><span class="glyphicon glyphicon-eye-open"></span>{{ article.click }}</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
                            {% endfor %}
                            {% include 'pagination.html' %}
						</div>
					</div>
					<div class="col-sm-2">
						<div class="panel panel-default">
							<div class="panel-heading">
								<div class="panel-title">
                                    <span class="glyphicon glyphicon-tags"></span>
									热门标签
								</div>
							</div>
							<div class="panel-body">
								{% for tag in tag_list %}
								<a href="#" class="label label-default">{{ tag }}</a>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
		</div>
	</div>
{% endblock %}

templates/article.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <title>{{ article.title }}</title>
{% endblock %}

{% block content %}
    {% load myfilter %}

    <div class="container" id="content">
		<div id="article-list-page">
			<div class="row">
				<div class="col-sm-3">
					<div class="sidebar left">
						<div class="list-group">
							<div id="sidebar-title" class="list-group-item">近期文章</div>
							<div id="item-list">
								{% for article in recent_articles %}
									<a class="list-group-item" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
                                    {% endfor %}
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-9">
					<div class="article-list">
						<div class="item">
							<div class="row">
								<div class="col-sm-2">
									<div class="date">
										<span class="day">{{ article.date_publish | date:'d' }}</span>
                                        <span class="month">{{ article.date_publish | date:'Y-m' }}</span>
									</div>
								</div>
								    <div class="col-sm-10" id="article_10">
									<div class="panel panel-default">
										<div class="panel-heading">
											<div class="panel-title">
												<span class="glyphicon glyphicon-book"></span>
												<span class="title">{{ article.title }}</span>
                                                <span id="article_id" style="display: none">{{ article.id }}</span>
											</div>
											<div class="small text-muted">
												<!-- <span class="blank"></span> -->
												<a href="#"><span class="glyphicon glyphicon-pushpin"></span>{{ article.category }}</a>-
                                                <a href="#"><span class="glyphicon glyphicon-user"></span>{{ article.author.username }}</a>-
                                                <span class="glyphicon glyphicon-tags"></span>
                                                {% for tag in article.tags.all %}
                                                    <a class="tags">{{ tag.name }}</a>
                                                {% endfor %}
											</div>
										</div>
										<div class="panel-body" id="article">
                                            {{ article.content | safe }}
										</div>
										<div class="panel-footer" id="aritcle_footer">
											<div class="small text-muted">
                                                {% if request.user.is_authenticated %}
												<a href="#0" title="赞"><span class="glyphicon glyphicon-heart {% if status %}like{% endif %}" id="like_login"></span><span id="likes_num">{{ article.likes_set.all.count }}</span></a>
                                                {% else %}
                                                    <a href="#0" title="登录后才可以点赞"><span class="glyphicon glyphicon-heart" id="like"></span>{{ article.likes_set.all.count }}</a>
                                                {% endif %}
                                                <a href="#"><span class="glyphicon glyphicon-comment"></span>{{ article.comments_set.all.count }}</a>
                                                <a href="#"><span class="glyphicon glyphicon-eye-open"></span>{{ article.views }}</a>
											</div>
										</div>
										<div class="comments">
                                            <form class="container" action="{% url 'comment_post' %}" role="form" method="post">
                                                {% csrf_token %}
												<div class="form-group" id="comment-form-group">
													<label for="comment">评论一下</label>
                                                    <input type="hidden" class="" name="pid" value="">
                                                    {{ comment_form.content }}
                                                    <input type="hidden" name="article" value="{{ article.id }}">
													<button name="submit" type="submit" value="Submit">评论</button>
												</div>
											</form>
											<div class="title">
												<h3>共{{  article.comments_set.all.count }}条评论</h3>
											</div>
                                            <div class="body">
                                                {% comment_tree comment_dict %}
                                            </div>
                                            <div class="" id="reply" style="display: none;">
                                                <form class="container" action="{% url 'comment_post' %}" id="reply_form" role="form" method="post">
                                                    {% csrf_token %}
                                                    <div class="form-group" id="reply_form_group">
                                                        <input type="hidden" class="parent_id" name="pid" value="">
                                                        {{ comment_form.content }}
                                                        <input type="hidden" name="article" value="{{ article.id }}">
                                                        <button name="submit" type="submit" value="Submit">回复</button>
                                                    </div>
                                                </form>
                                            </div>

										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/article_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>文章编辑</title>
{% endblock %}

{% block content %}
    <div class="container" id="content">
        <div class="article_cloth">
            <form action="{% url 'article_edit' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                     <div class="form-group">
                        <label for="title" class="control-label">标题</label>
                         {{ article_editform.title }}
                        <span style="color: red">{{ article_editform.title.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="description" class="control-label">文章摘要</label>
                        {{ article_editform.description }}
                         <span style="color: red">{{ article_editform.description.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="article_content" class="control-label">文章内容</label>
                        {{ article_editform.content }}
                        <span style="color: red">{{ article_editform.content.errors }}</span>
                    </div>
                        <br>
                    <div class="form-group">
                        <label for="photo" class="col-sm-2 control-label">主页图片</label>
                        <div class="col-sm-10">
                            {{ article_editform.photo }}
                        </div>
                    </div>
                        <br>
                        <br>
                    <div class="form-group">
                        <label for="article_tags" class="col-sm-2 control-label">标签</label>
                        <div class="col-sm-10">
                            {{ article_editform.tagstext }}
                            <span style="color: red">{{ article_editform.tagstext.errors }}</span>
                        </div>
                    </div>
                    <br>
                        {{ article_editform.article_id }}
                    <br>
                <div class="form-group">
                      <button type="submit" class="btn btn-article">提交修改</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/article_list.html
{% extends 'base.html' %}

{% block title %}
    <title>技术</title>
{% endblock %}


{% block content %}
    <div class="container" id="content">
		<div id="article-list-page">
				<div class="row">
					<div class="col-sm-3">
						<div class="sidebar left">
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">近期文章</div>
								<div id="item-list">
                                    {% for article in recent_articles %}
									<a class="list-group-item" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
                                    {% endfor %}
								</div>
							</div>
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">文章归档</div>
								<div id="item-list">
                                    {% for archive in archive_list %}
									<a class="list-group-item" href="{% url 'archive' %}?menu_name={{ menu_name }}&year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}" target="_blank">{{ archive }}</a>
									{% endfor %}
								</div>
							</div>

							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">分类目录</div>
								<div id="item-list">
                                    {% for category in category_list %}
									<a class="list-group-item" href="{% url 'category' %}?menu_name={{ menu_name }}&category={{ category }}" target="_blank">{{ category }}</a>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="article-list">
                            {% for article in pages %}
							<div class="item">
								<div class="row">
									<div class="col-sm-2">
										<div class="date">
											<span class="day">{{ article.date_publish | date:'d' }}</span>
											<span class="month">{{ article.date_publish | date:'Y-m' }}</span>
										</div>
									</div>
									<div class="col-sm-10">
										<div class="panel panel-default">
											<div class="panel-heading">
												<div class="panel-title">
													<div class="row">
														<div class="col-sm-1">
															<span class="glyphicon glyphicon-book"></span>
														</div>
														<div class="col-sm-11">
															<a class="title" href="{% url 'article' %}?menu_name={{ menu }}&id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
														</div>
													</div>
												</div>
												<div class="small text-muted">
													<!-- <span class="blank"></span> -->
													<a href="#0"><span class="glyphicon glyphicon-pushpin"></span>{{ article.category }}</a>-
													<a href="#0"><span class="glyphicon glyphicon-user"></span>{{ article.author.username }}</a>-
													<span class="glyphicon glyphicon-tags"></span>
                                                    {% for tag in article.tags.all %}
													    <a class="tags" href="{% url 'tagpage' %}?menu_name={{ menu_name }}&tag={{ tag }}" target="_blank">{{ tag.name }}</a>
                                                    {% endfor %}
												</div>
											</div>
											<div class="panel-body">
												{{ article.description}}
											</div>
											<div class="panel-footer">
												<div class="small text-muted">
													<a><span class="glyphicon glyphicon-heart"></span>{{ article.likes_set.all.count }}</a>
													<a><span class="glyphicon glyphicon-comment"></span>{{ article.comments_set.all.count }}</a>
													<a><span class="glyphicon glyphicon-eye-open"></span>{{ article.views }}</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
                            {% endfor %}
                            {% include 'pagination.html' %}
						</div>
					</div>
					<div class="col-sm-2">
						<div class="panel panel-default">
							<div class="panel-heading">
								<div class="panel-title">
                                    <span class="glyphicon glyphicon-tags"></span>
									热门标签
								</div>
							</div>
							<div class="panel-body">
                                {% for tag in tag_list %}
								<a href="{% url 'tagpage' %}?menu_name={{ menu_name }}&tag={{ tag }}" target="_blank" class="label label-default">{{ tag }}</a>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
		</div>
	</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ category }}类文章</title>
{% endblock %}


{% block content %}
    <div class="container" id="content">
		<div id="article-list-page">
				<div class="row">
					<div class="col-sm-3">
						<div class="sidebar left">
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">近期文章</div>
								<div id="item-list">
									{% for article in recent_articles %}
									<a class="list-group-item" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
                                    {% endfor %}
								</div>
							</div>
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">文章归档</div>
								<div id="item-list">
                                    {% for archive in archive_list %}
									<a class="list-group-item" href="#">{{ archive }}</a>
									{% endfor %}
								</div>
							</div>

							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">分类目录</div>
								<div id="item-list">
									<a class="list-group-item" href="#">{{ category }}</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="article-list">
                            {% for article in pages %}
							<div class="item">
								<div class="row">
									<div class="col-sm-2">
										<div class="date">
											<span class="day">{{ article.date_publish | date:'d' }}</span>
											<span class="month">{{ article.date_publish | date:'Y-m' }}</span>
										</div>
									</div>
									<div class="col-sm-10">
										<div class="panel panel-default">
											<div class="panel-heading">
												<div class="panel-title">
													<div class="row">
														<div class="col-sm-1">
															<span class="glyphicon glyphicon-book"></span>
														</div>
														<div class="col-sm-11">
															<a class="title" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
														</div>
													</div>
												</div>
												<div class="small text-muted">
													<!-- <span class="blank"></span> -->
													<a href="#"><span class="glyphicon glyphicon-pushpin"></span>{{ article.category }}</a>-
													<a href="#"><span class="glyphicon glyphicon-user"></span>{{ article.author.username }}</a>-
													<span class="glyphicon glyphicon-tags"></span>
                                                    {% for tag in article.tags.all %}
													    <a class="tags" href="#">{{ tag.name }}</a>
                                                    {% endfor %}
												</div>
											</div>
											<div class="panel-body">
												{{ article.description}}
											</div>
											<div class="panel-footer">
												<div class="small text-muted">
													<a href="#"><span class="glyphicon glyphicon-heart"></span>{{ article.likes }}</a>
													<a href="#"><span class="glyphicon glyphicon-comment"></span>{{ article.comments_set.all.count }}</a>
													<a href="#"><span class="glyphicon glyphicon-eye-open"></span>{{ article.click }}</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
                            {% endfor %}
                            {% include 'pagination.html' %}
						</div>
					</div>
					<div class="col-sm-2">
						<div class="panel panel-default">
							<div class="panel-heading">
								<div class="panel-title">
                                    <span class="glyphicon glyphicon-tags"></span>
									热门标签
								</div>
							</div>
							<div class="panel-body">
								{% for tag in tag_list %}
								<a href="#" class="label label-default">{{ tag }}</a>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
		</div>
	</div>
{% endblock %}

templates/life.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <title>生活</title>
{% endblock %}

{% block content %}
    <div class="container" id="content">
		<div id="article-list-page">
				<div class="row">
					<div class="col-sm-3">
						<div class="sidebar left">
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">近期文章</div>
								<div id="item-list">
                                    {% for article in recent_articles %}
									<a class="list-group-item" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title }}">{{ article.title }}</a>
                                    {% endfor %}
								</div>
							</div>
							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">文章归档</div>
								<div id="item-list">
                                    {% for archive in archive_list %}
									<a class="list-group-item" href="{% url 'archive' %}?menu_name={{ menu_name }}&year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}" target="_blank">{{ archive }}</a>
									{% endfor %}
								</div>
							</div>

							<div class="list-group">
								<div id="sidebar-title" class="list-group-item">分类目录</div>
								<div id="item-list">
                                    {% for category in category_list %}
									<a class="list-group-item" href="{% url 'category' %}?menu_name={{ menu_name }}&category={{ category }}" target="_blank">{{ category }}</a>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="article-list">
                            {% for article in pages %}
							<div class="item">
								<div class="row">
									<div class="col-sm-2">
										<div class="date">
											<span class="day">{{ article.date_publish | date:'d' }}</span>
											<span class="month">{{ article.date_publish | date:'Y-m' }}</span>
										</div>
									</div>
									<div class="col-sm-10">
										<div class="panel panel-default">
											<div class="panel-heading">
												<div class="panel-title">
													<div class="row">
														<div class="col-sm-1">
															<span class="glyphicon glyphicon-book"></span>
														</div>
														<div class="col-sm-11">
															<a class="title" href="{% url 'article' %}?id={{ article.id }}" target="_blank" title="{{ article.title}}">{{ article.title }}</a>
														</div>
													</div>
												</div>
												<div class="small text-muted">
													<!-- <span class="blank"></span> -->
													<a href="#"><span class="glyphicon glyphicon-pushpin"></span>{{ article.category }}</a>-
													<a href="#"><span class="glyphicon glyphicon-user"></span>{{ article.author.username }}</a>-
													<span class="glyphicon glyphicon-tags"></span>
                                                    {% for tag in article.tags.all %}
													<a class="tags" href="#">{{ tag.name }}</a>
                                                    {% endfor %}
												</div>
											</div>
											<div class="panel-body">
												<div class="row">
													<div class="col-sm-5">
														<a href="#" id="life_pic">
															<img src="/uploads/{{ article.photo }}" alt="pic">
														</a>

													</div>
													<div class="col-sm-7">
														{{ article.description }}
													</div>
												</div>

											</div>
											<div class="panel-footer">
												<div class="small text-muted">
													<a href="#"><span class="glyphicon glyphicon-heart"></span>{{ article.likes_set.all.count }}</a>
													<a href="#"><span class="glyphicon glyphicon-comment"></span>{{ article.comments_set.all.count }}</a>
													<a href="#"><span class="glyphicon glyphicon-eye-open"></span>{{ article.views }}</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
                            {% endfor %}
                            {% include 'pagination.html' %}
						</div>
					</div>
					<div class="col-sm-2">
						<div class="panel panel-default">
							<div class="panel-heading">
								<div class="panel-title">
									<span class="glyphicon glyphicon-tags"></span>
									热门标签
								</div>
							</div>
							<div class="panel-body">
                                {% for tag in tag_list %}
								<a href="{% url 'tagpage' %}?menu_name={{ menu_name }}&tag={{ tag }}" target="_blank" class="label label-default">{{ tag }}</a>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
		</div>
	</div>
{% endblock %}